name: continuous integration
on: 
  push:
    paths:
    - 'Dockerfile'
    - '.github/workflows/ci.yml'

jobs:
  build:
    name: docker build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🐳 Docker build
      uses: docker/build-push-action@v1
      with:
        registry: krogertechnologyprodusw-docker-local-dev.jfrog.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: test/artifact
        tags: ${{ github.sha }},latest
        tag_with_ref: true
        add_git_labels: true
        always_pull: true
    - name: 🐳 Promote Docker image
      uses: timperman/artifactory-promote-action@v1
      with:
        url: https://krogertechnologyprodusw.jfrog.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        sourceRepo: docker-local-dev
        targetRepo: docker-local-test
        dockerRepository: test/artifact
        tag: ${{ github.sha }}
        targetTag: latest
